public enum NodeType {
    PROGRAM,
    VARIABLE_DECLARATION,
    FUNCTION_DECLARATION,
    PARAMETER_LIST,
    BLOCK,
    DISPLAY_STATEMENT,
    FUNCTION_CALL,
    BINARY_EXPRESSION,
    UNARY_EXPRESSION,
    IDENTIFIER,
    INTEGER_LITERAL,
    STRING_LITERAL,
    OPERATOR
}