public enum TokenType {
    LET,
    FUNCTION,
    MAIN,
    DISPLAY,
    OPEN_BRACE,
    CLOSE_BRACE,
    OPEN_PAREN,
    CLOSE_PAREN,
    SEMICOLON,
    VARIABLE_REFERENCE,
    IDENTIFIER,
    EOF, STRING_LITERAL, VARIABLE, NUMBER, LEFT_PAREN, INTEGER
}
